[2023-03-20 16:20:31,417] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: to_posgrest_v4.5.create_postgres_table_business manual__2023-03-20T16:20:18.485887+00:00 [queued]>
[2023-03-20 16:20:31,454] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: to_posgrest_v4.5.create_postgres_table_business manual__2023-03-20T16:20:18.485887+00:00 [queued]>
[2023-03-20 16:20:31,455] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-03-20 16:20:31,456] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-03-20 16:20:31,457] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-03-20 16:20:31,497] {taskinstance.py:1259} INFO - Executing <Task(PostgresOperator): create_postgres_table_business> on 2023-03-20 16:20:18.485887+00:00
[2023-03-20 16:20:31,502] {standard_task_runner.py:52} INFO - Started process 13950 to run task
[2023-03-20 16:20:31,509] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'to_posgrest_v4.5', 'create_postgres_table_business', 'manual__2023-03-20T16:20:18.485887+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/to_postgresql.py', '--cfg-path', '/tmp/tmpge0fgg30', '--error-file', '/tmp/tmp40fpff93']
[2023-03-20 16:20:31,512] {standard_task_runner.py:77} INFO - Job 109: Subtask create_postgres_table_business
[2023-03-20 16:20:31,921] {logging_mixin.py:109} INFO - Running <TaskInstance: to_posgrest_v4.5.create_postgres_table_business manual__2023-03-20T16:20:18.485887+00:00 [running]> on host 0b4cdb459521
[2023-03-20 16:20:32,259] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=sakabuana31
AIRFLOW_CTX_DAG_ID=to_posgrest_v4.5
AIRFLOW_CTX_TASK_ID=create_postgres_table_business
AIRFLOW_CTX_EXECUTION_DATE=2023-03-20T16:20:18.485887+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-20T16:20:18.485887+00:00
[2023-03-20 16:20:32,339] {base.py:79} INFO - Using connection to: id: postgres_localhost. Host: host.docker.internal, Port: 5432, Schema: final, Login: ***, Password: ***, extra: {}
[2023-03-20 16:20:32,435] {dbapi.py:225} INFO - Running statement: 
            create table if not exists business (
                business_id text PRIMARY KEY,
                name text,
                address text,
                city text,
                state text,
                postal_code text,
                latitude float,
                longitude float,
                stars float,
                review_count int,
                is_open int,
                attributes text,
                categories text,
                hours text
            ) 
        , parameters: None
[2023-03-20 16:20:32,440] {postgres.py:71} INFO - NOTICE:  relation "business" already exists, skipping

[2023-03-20 16:20:32,534] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=to_posgrest_v4.5, task_id=create_postgres_table_business, execution_date=20230320T162018, start_date=20230320T162031, end_date=20230320T162032
[2023-03-20 16:20:32,597] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-03-20 16:20:32,833] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
