[2023-03-20 14:17:57,172] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: to_posgrest_v3.4.read_csv_to_temp_table manual__2023-03-20T14:16:19.614864+00:00 [queued]>
[2023-03-20 14:17:57,209] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: to_posgrest_v3.4.read_csv_to_temp_table manual__2023-03-20T14:16:19.614864+00:00 [queued]>
[2023-03-20 14:17:57,210] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-03-20 14:17:57,211] {taskinstance.py:1239} INFO - Starting attempt 2 of 3
[2023-03-20 14:17:57,211] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-03-20 14:17:57,250] {taskinstance.py:1259} INFO - Executing <Task(PostgresOperator): read_csv_to_temp_table> on 2023-03-20 14:16:19.614864+00:00
[2023-03-20 14:17:57,254] {standard_task_runner.py:52} INFO - Started process 8283 to run task
[2023-03-20 14:17:57,261] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'to_posgrest_v3.4', 'read_csv_to_temp_table', 'manual__2023-03-20T14:16:19.614864+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/to_postgresql.py', '--cfg-path', '/tmp/tmp4f0vhw19', '--error-file', '/tmp/tmprat8lr70']
[2023-03-20 14:17:57,263] {standard_task_runner.py:77} INFO - Job 40: Subtask read_csv_to_temp_table
[2023-03-20 14:17:57,549] {logging_mixin.py:109} INFO - Running <TaskInstance: to_posgrest_v3.4.read_csv_to_temp_table manual__2023-03-20T14:16:19.614864+00:00 [running]> on host 0b4cdb459521
[2023-03-20 14:17:57,856] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=sakabuana31
AIRFLOW_CTX_DAG_ID=to_posgrest_v3.4
AIRFLOW_CTX_TASK_ID=read_csv_to_temp_table
AIRFLOW_CTX_EXECUTION_DATE=2023-03-20T14:16:19.614864+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-20T14:16:19.614864+00:00
[2023-03-20 14:17:57,935] {base.py:79} INFO - Using connection to: id: postgres_localhost. Host: host.docker.internal, Port: 5432, Schema: final, Login: ***, Password: ***, extra: {}
[2023-03-20 14:17:58,009] {dbapi.py:225} INFO - Running statement: 
            CREATE TEMPORARY TABLE temp_temperature (
                date DATE PRIMARY KEY,
                min DECIMAL(5, 2),
                max DECIMAL(5, 2),
                normal_min DECIMAL(5, 2),
                normal_max DECIMAL(5, 2),
                mean DECIMAL(5, 2),
                status_temp int
            );

            COPY temp_temperature FROM '/opt/***/data/output-csv/dataclean-temperature-lasvegas.csv' DELIMITER ',' CSV HEADER;
            INSERT INTO temperature (date, min, max, normal_min, normal_max, mean, status_temp)
            SELECT date, min, max, normal_min, normal_max, mean, status_temp
            FROM temp_temperature
            ON CONFLICT (date) DO NOTHING;
        , parameters: None
[2023-03-20 14:17:58,107] {dbapi.py:233} INFO - Rows affected: 26588
[2023-03-20 14:17:58,208] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=to_posgrest_v3.4, task_id=read_csv_to_temp_table, execution_date=20230320T141619, start_date=20230320T141757, end_date=20230320T141758
[2023-03-20 14:17:58,290] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-03-20 14:17:58,484] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
