[2023-03-20 19:01:41,479] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: to_posgrest_v4.9.create_postgres_table manual__2023-03-20T19:01:39.369448+00:00 [queued]>
[2023-03-20 19:01:41,516] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: to_posgrest_v4.9.create_postgres_table manual__2023-03-20T19:01:39.369448+00:00 [queued]>
[2023-03-20 19:01:41,517] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-03-20 19:01:41,518] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-03-20 19:01:41,519] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-03-20 19:01:41,557] {taskinstance.py:1259} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2023-03-20 19:01:39.369448+00:00
[2023-03-20 19:01:41,563] {standard_task_runner.py:52} INFO - Started process 22975 to run task
[2023-03-20 19:01:41,573] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'to_posgrest_v4.9', 'create_postgres_table', 'manual__2023-03-20T19:01:39.369448+00:00', '--job-id', '231', '--raw', '--subdir', 'DAGS_FOLDER/to_postgresql.py', '--cfg-path', '/tmp/tmp8ylztba1', '--error-file', '/tmp/tmpgmpnr2f8']
[2023-03-20 19:01:41,576] {standard_task_runner.py:77} INFO - Job 231: Subtask create_postgres_table
[2023-03-20 19:01:41,872] {logging_mixin.py:109} INFO - Running <TaskInstance: to_posgrest_v4.9.create_postgres_table manual__2023-03-20T19:01:39.369448+00:00 [running]> on host 0b4cdb459521
[2023-03-20 19:01:42,190] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=sakabuana31
AIRFLOW_CTX_DAG_ID=to_posgrest_v4.9
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2023-03-20T19:01:39.369448+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-20T19:01:39.369448+00:00
[2023-03-20 19:01:42,272] {base.py:79} INFO - Using connection to: id: postgres_localhost. Host: host.docker.internal, Port: 5432, Schema: final, Login: ***, Password: ***, extra: {}
[2023-03-20 19:01:42,351] {dbapi.py:225} INFO - Running statement: 
            create table if not exists temperature (
                date DATE PRIMARY KEY,
                min DECIMAL(5, 2),
                max DECIMAL(5, 2),
                normal_min DECIMAL(5, 2),
                normal_max DECIMAL(5, 2),
                mean DECIMAL(5, 2),
                status_temp int
            ) 
        , parameters: None
[2023-03-20 19:01:42,355] {postgres.py:71} INFO - NOTICE:  relation "temperature" already exists, skipping

[2023-03-20 19:01:42,443] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=to_posgrest_v4.9, task_id=create_postgres_table, execution_date=20230320T190139, start_date=20230320T190141, end_date=20230320T190142
[2023-03-20 19:01:42,506] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-03-20 19:01:42,748] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
