[2023-03-20 19:01:52,343] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: to_posgrest_v4.9.create_postgres_table_business manual__2023-03-20T19:01:39.369448+00:00 [queued]>
[2023-03-20 19:01:52,390] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: to_posgrest_v4.9.create_postgres_table_business manual__2023-03-20T19:01:39.369448+00:00 [queued]>
[2023-03-20 19:01:52,392] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-03-20 19:01:52,393] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-03-20 19:01:52,394] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-03-20 19:01:52,455] {taskinstance.py:1259} INFO - Executing <Task(PostgresOperator): create_postgres_table_business> on 2023-03-20 19:01:39.369448+00:00
[2023-03-20 19:01:52,462] {standard_task_runner.py:52} INFO - Started process 22991 to run task
[2023-03-20 19:01:52,470] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'to_posgrest_v4.9', 'create_postgres_table_business', 'manual__2023-03-20T19:01:39.369448+00:00', '--job-id', '235', '--raw', '--subdir', 'DAGS_FOLDER/to_postgresql.py', '--cfg-path', '/tmp/tmpfmdnm1k2', '--error-file', '/tmp/tmpvrmvd96a']
[2023-03-20 19:01:52,473] {standard_task_runner.py:77} INFO - Job 235: Subtask create_postgres_table_business
[2023-03-20 19:01:52,779] {logging_mixin.py:109} INFO - Running <TaskInstance: to_posgrest_v4.9.create_postgres_table_business manual__2023-03-20T19:01:39.369448+00:00 [running]> on host 0b4cdb459521
[2023-03-20 19:01:53,103] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=sakabuana31
AIRFLOW_CTX_DAG_ID=to_posgrest_v4.9
AIRFLOW_CTX_TASK_ID=create_postgres_table_business
AIRFLOW_CTX_EXECUTION_DATE=2023-03-20T19:01:39.369448+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-20T19:01:39.369448+00:00
[2023-03-20 19:01:53,182] {base.py:79} INFO - Using connection to: id: postgres_localhost. Host: host.docker.internal, Port: 5432, Schema: final, Login: ***, Password: ***, extra: {}
[2023-03-20 19:01:53,258] {dbapi.py:225} INFO - Running statement: 
            create table if not exists business (
                business_id text PRIMARY KEY,
                name text,
                address text,
                city text,
                state text,
                postal_code text,
                latitude float,
                longitude float,
                stars float,
                review_count int,
                is_open int,
                attributes text,
                categories text,
                hours text
            ) 
        , parameters: None
[2023-03-20 19:01:53,262] {postgres.py:71} INFO - NOTICE:  relation "business" already exists, skipping

[2023-03-20 19:01:53,350] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=to_posgrest_v4.9, task_id=create_postgres_table_business, execution_date=20230320T190139, start_date=20230320T190152, end_date=20230320T190153
[2023-03-20 19:01:53,431] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-03-20 19:01:53,670] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
